### ISSUE TITLE
Workbook explaining chainIds

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum.Workbooks#10]
From the EIP155 signing includes the chainId. (Explain why EIP155 and attacks replaying transactions if sharing the same account private keys across chains)

Preconfigured chainIds can be found in Nethereum.Signer.Chain
```csharp
public enum Chain
    {
        MainNet = 1,
        Morden = 2,
        Ropsten = 3,
        Rinkeby = 4,
        RootstockMainNet = 30,
        RootstockTestNet = 31,
        Kovan = 42,
        ClassicMainNet = 61,
        ClassicTestNet = 62,
        Private = 1337
    }
```
to simplify the signing the Account includes the chainId like:
```csharp
var account = new Account("privateKey"), Chain.MainNet);
```
or
```
 account =  new Account(PrivateKey, 444444444500);
```
the rest is the same.

To configure in geth the chainId, edit the genesis as follows (example configuration from clique)
```json
"config": {
    "chainID": 444444444500,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "clique": {
      "period": 1,
      "epoch": 30000
    }
```

Include a sample of Account Transfer, get Balance.

**Comment by anegg0** [comment]
Can I delete this issue? This workbook has been created.

**Comment by juanfranblanco** [comment]
Did you see my edits and validate them?

**Comment by anegg0** [comment]
Oh no, I didn't see your edits. On it now.

Gaël Blanchemain

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
