### ISSUE TITLE
A workbook or doc explaining different unit conversation, gas price, ether,

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum.Workbooks#22]
Also, how to send a transaction and convert all units to wei.

**Comment by anegg0** [comment]
done in: https://github.com/anegg0/Nethereum.Workbooks/blob/unit-conversion/docs/nethereum-converting-units.workbook and https://github.com/anegg0/Nethereum.Workbooks/blob/gas-estimate/docs/nethereum-estimating-gas.workbook
