### ISSUE TITLE
Procedure to update the workbooks to the latest release of Nethereum and Geth (Parity, Quorum too)

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum.Workbooks#4]
A procedure, hopefully, automated should be created to update the Workbooks to the latest Nethereum and clients integration.

My thoughts are for a living documentation to:

* Create the workbooks as unit tests
* The explanations can be comments, generic explanations can be added as a key or something.
* Workbooks are generated by extracting them from the Unit tests.
* Unit tests are generic integration tests, win, win, win.

**Comment by KevinSmall** [comment]
Hi Juan,

I might be able to contribute here. Can you provide some more details?

Thanks, Kevin.

**Comment by juanfranblanco** [comment]
Hi @KevinSmall ,

The problem is something very generic, the issue is that workbooks are not easily upgradable or testable. So the idea is to extract them from unit tests.

I am working on a simple text extractor for this, using regions as the areas to use as code or markdown text.

**Comment by juanfranblanco** [comment]
This is mostly done, creating a new workbook only to refresh the versions of nugets.
